### ISSUE TITLE
Spectre breaks push notifications.

### ISSUE THREAD

**Issue by Slanderrr** [CokePokes/cokepokes.github.io#4]
I am using Snapchat v10.31.0 and I have been using Spectre beta since you released it. The last couple updates have sorta broken my push notifications. I even tried updating to the latest version of Snapchat supported by Spectre v0.3-20 and the notifications still don't work. After removing Spectre, my notifications worked perfectly fine.

**Comment by CokePokes** [comment]
This is a cydia repo, not support for one individual tweak on it.
